<template>
  <div class="h-screen grid grid-cols-3 gap-5 px-5" style="grid-template-rows: max-content 1fr">
    <div v-if="settings !== null" class="grid grid-cols-2 top-0 left-0 h-full w-full max-h-full overflow-y-auto p-5 gap-20 fixed z-20 bg-white">
      <div class="absolute top-0 right-0 mt-5 mr-5">
        <span title="Close settings" class="cursor-pointer" @click='closeSettings'>
          <XIcon class="stroke-1 text-gray-400 hover:text-teal-400" size="2x"></XIcon>
        </span>
      </div>
      <div>
        <div class="text-xl">Server settings</div>
        <p class="text-xs text-gray-700 my-2">Server settings</p>
        <p class="mb-1 mt-3">Target host:</p>
        <input v-model='settings.server.host' type="text" placeholder="localhost:25565" class="bg-white border-b-2 focus:border-teal-400 focus:outline-none rounded py-2 px-4 block w-full appearance-none leading-normal placeholder-gray-600 focus:shadow">
        <p class="mb-1 mt-3">Proxy port:</p>
        <input v-model='settings.server.proxyPort' type="text" placeholder="25566" class="bg-white border-b-2 focus:border-teal-400 focus:outline-none rounded py-2 px-4 block w-full appearance-none leading-normal placeholder-gray-600 focus:shadow">
      </div>
      <div>
        <div class="text-xl">Ignored packets (custom)</div>
        <p class="text-xs text-gray-700 my-2">Packets that will not be sent by server to the debugger.</p>
        <div class="relative mb-4">
          <search :packets="search.packets" v-model="search.query" ref="settingsSearch" @select="settingsSelectPacket"></search>
        </div>

        <div class="overflow-y-auto">
          <template v-for="(_, packet) in settings.ignoredPackets.custom">
            <div v-if="settings.ignoredPackets.custom[packet]" class="text-xs inline-flex items-center bg-teal-400 rounded-full p-1 pl-3 mr-2 mb-2 text-white border-b-2 border-teal-600">
              <pre>{{packet}}</pre>
              <div class="ml-1 hover:bg-red-600 hover:text-white text-red-400 p-1 rounded-full cursor-pointer" @click='settings.ignoredPackets.custom[packet] = false'>
                <XIcon size="1.2x"></XIcon>
              </div>
            </div>
          </template>
        </div>
        <div class="text-xl mt-10">Ignored packets (game)</div>
        <p class="text-xs text-gray-700 my-2">Packets generated by game (time/ping)</p>
        <template v-for="(_, packet) in settings.ignoredPackets.game">
          <div @click='settings.ignoredPackets.game[packet] = !settings.ignoredPackets.game[packet]' class="text-xs flex items-center pb-3 pt-4 border-b border-gray-300 group cursor-pointer select-none">
            <pre class="text-gray-900">{{packet}}</pre>
            <CheckSquareIcon class="ml-auto mr-4 text-teal-400" v-if="settings.ignoredPackets.game[packet]" size="1.5x"></CheckSquareIcon>
            <SquareIcon class="ml-auto mr-4 text-gray-700 group-hover:text-teal-400" v-else size="1.5x"></SquareIcon>
          </div>
        </template>
        <div class="text-xl mt-10">Ignored packets (world)</div>
        <p class="text-xs text-gray-700 my-2">Packets generated by world events (chunk loading/unloading)</p>
        <template v-for="(_, packet) in settings.ignoredPackets.world">
          <div @click='settings.ignoredPackets.world[packet] = !settings.ignoredPackets.world[packet]' class="text-xs flex items-center pb-3 pt-4 border-b border-gray-300 group cursor-pointer select-none">
            <pre class="text-gray-900">{{packet}}</pre>
            <CheckSquareIcon class="ml-auto mr-4 text-teal-400" v-if="settings.ignoredPackets.world[packet]" size="1.5x"></CheckSquareIcon>
            <SquareIcon class="ml-auto mr-4 text-gray-700 group-hover:text-teal-400" v-else size="1.5x"></SquareIcon>
          </div>
        </template>
        <div class="text-xl mt-10">Ignored packets (entity)</div>
        <p class="text-xs text-gray-700 my-2">Packets generated by entities (spawn/despawn/move)</p>
        <template v-for="(_, packet) in settings.ignoredPackets.entity">
          <div @click='settings.ignoredPackets.entity[packet] = !settings.ignoredPackets.entity[packet]' class="text-xs flex items-center pb-3 pt-4 border-b border-gray-300 group cursor-pointer select-none">
            <pre class="text-gray-900">{{packet}}</pre>
            <CheckSquareIcon class="ml-auto mr-4 text-teal-400" v-if="settings.ignoredPackets.entity[packet]" size="1.5x"></CheckSquareIcon>
            <SquareIcon class="ml-auto mr-4 text-gray-700 group-hover:text-teal-400" v-else size="1.5x"></SquareIcon>
          </div>
        </template>
      </div>
      <div class="col-span-4 pb-5">
        <a @click="closeSettings" class="cursor-pointer text-white bg-teal-400 px-4 py-2 rounded float-right">
          <SaveIcon class="float-left mr-2" size="1.5x"></SaveIcon>
          Save settings
        </a>
      </div>
    </div>
    <div v-if="record.state !== 0 && settings === null" class="fixed top-0 left-0 h-screen w-screen z-10 flex items-center justify-center" style="background: rgba(255, 255, 255, .75)">
      <div class="absolute bottom-0 left-0 mb-5 ml-5 text-xs text-gray-700">
        Recording on {{ host }} at {{ version }}
      </div>
      <div class="absolute top-0 right-0 mt-5 mr-5">
        <span v-if="settings === null && record.state === -1" title="Open settings" class="cursor-pointer mr-5" @click='openSettings'>
          <SettingsIcon class="stroke-1 text-gray-400 hover:text-teal-400" size="2x"></SettingsIcon>
        </span>
      </div>
      <div class="grid gap-2" style="grid-template-columns: min-content 1fr">
        <div class="flex items-center">
          <span v-if="record.state === 1" title="Stop recording new packets" class="cursor-pointer mr-5" @click='stopRecording'>
            <PauseCircleIcon class="stroke-1 text-teal-400" size="2x"></PauseCircleIcon>
          </span>
          <span v-else-if="record.state === -1" title="Start recording new packets" class="cursor-pointer mr-5" @click='startRecording'>
            <PlayCircleIcon class="stroke-1 text-teal-400" size="2x"></PlayCircleIcon>
          </span>
          <span v-else-if="record.state === 2" class="mr-5">
            <LoaderIcon class="stroke-1 text-teal-400 loading-anim" size="2x"></LoaderIcon>
          </span>
        </div>
        <div style="width: 350px">
          <div v-if="record.state === 1" class="text-xl">Stop recording packages</div>
          <div v-if="record.state === -1" class="text-xl">Start recording packages</div>
          <div v-if="record.state === 2" class="text-xl">Loading data</div>
          <div class="text-xs mt-2 text-gray-700">{{ record.messageQueue.length }} / 2048 ({{ record.messageQueue.length / 20.48 ^ 0 }}%) Buffer</div>
          <div class="bg-gray-300 h-1 rounded mt-2">
            <div class="h-1 bg-teal-400" :style="{ width: record.messageQueue.length / 20.48 + '%' }"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-span-2 rounded shadow-lg bg-white px-6 py-4 my-5">
      <div class="text-gray-400 flex items-center justify-center">
        <div @click='openSettings' title="Open settings" class="mr-auto text-gray-800 flex items-center cursor-pointer group">
          <SettingsIcon class="stroke-1 mr-2 text-gray-400 group-hover:text-teal-400" size="2x"></SettingsIcon>
          <div>
            Settings
            <span class="text-xs block text-gray-700">
            Open settings
          </span>
          </div>
        </div>

        <div @click='startRecording' title="Start recording" class="text-gray-800 flex items-center cursor-pointer group">
          <PlayCircleIcon class="stroke-1 mr-2 text-gray-400 group-hover:text-teal-400" size="2x"></PlayCircleIcon>
          <div>
            Record
            <span class="text-xs block text-gray-700">
              Start monitoring packets
          </span>
          </div>
        </div>

        <div @click='packets = []' title="Remove all packets from buffer" class=" ml-auto text-gray-800 flex items-center cursor-pointer group">
          <div class="text-right mr-2">
            Clear
            <span class="text-xs block text-gray-700">
              Remove all packets
          </span>
          </div>
          <TrashIcon class="stroke-1 text-gray-400 group-hover:text-teal-400" size="2x"></TrashIcon>
        </div>
      </div>
    </div>
    <div class="rounded shadow-lg bg-white px-6 py-4 my-5 relative">
      <search :packets="search.packets" v-model="search.query"></search>
    </div>
    <div class="col-span-2 relative my-5 rounded shadow-lg overflow-y-auto max-h-full" id="packets">
      <div v-for="packet in packets">
        <template v-if="isFiltered(packet)">
          <!--          Transition -->
          <div class="py-4 px-6 cursor-pointer" @click='open(packet)'>
            <div class="flex">

              <UploadCloudIcon v-if="packet.to === 1" class="stroke-1 mr-2 text-green-400" size="1.5x"></UploadCloudIcon>
              <DownloadCloudIcon v-if="packet.to === 0" class="stroke-1 mr-2 text-blue-400" size="1.5x"></DownloadCloudIcon>

              <pre>{{packet.meta.name}}</pre>
              <div class="ml-auto">
                <div class="text-gray-400 hover:text-teal-400 cursor-pointer" @click.stopPropagation='filters[packet.meta.name] = true'>
                  <FilterIcon size="1.2x"/>
                </div>
              </div>
            </div>
          </div>
          <!--        Transition -->
          <div v-if="packet === id_open" class="px-6">
            <div class="border-b border-gray-200 mb-4"></div>
            <div class="grid mb-4" style="grid-template-columns:min-content 1fr">
              <div>
                <div class="flex-1 text-sm" v-for="(tab, idx) in tabs">
                  <a :class="{ 'text-teal-400': id_tab === idx, 'hover:text-teal-400 text-gray-600': id_tab !== idx }" class="cursor-pointer block py-2 px-8" @click="id_tab = idx">{{ tab }}</a>
                </div>
              </div>
              <div class="ml-4">
                <pre v-if="id_tab === 0" class="text-xs rounded bg-gray-100 p-4" v-html="formatJSON(packet.data)"></pre>
                <pre v-if="id_tab === 1" class="text-xs rounded bg-gray-100 p-4" v-html="formatJSON(packet.meta)"></pre>
                <pre v-if="id_tab === 2" class="text-xs p-4">
                  <!-- TODO: Add format data -->
                </pre>
              </div>
            </div>
          </div>

          <div class="border-b border-gray-300"></div>
        </template>
      </div>
    </div>
    <div class="p-5 row-span-2 grid" style="grid-template-rows: min-content 1fr">
      <div class="pb-2">
        <span class="text-xl">
          Filtered packets
        </span>
        <div v-if="Object.keys(filters).length" @click='filters = Object.create(null)' title="Clear all filters" class="float-right text-gray-800 flex items-center cursor-pointer group">
          <div class="text-right mr-2">
            Clear
            <span class="text-xs block text-gray-700">
              Remove all filters
          </span>
          </div>
          <TrashIcon class="stroke-1 text-gray-400 group-hover:text-teal-400" size="2x"></TrashIcon>
        </div>
      </div>
      <div class="overflow-y-auto h-full">
        <template v-for="(packet) in filters">
          {{ packet }}
          <div v-if="filters[packet]" @click='filters[packet] = false' class="flex items-center pb-3 pt-4 border-b border-gray-300 group cursor-pointer">
            <pre class="text-xs">{{packet}}</pre>
            <XIcon class="ml-auto mr-4 group-hover:bg-red-600 group-hover:text-white text-red-400 p-1 rounded" size="1.2x"></XIcon>
          </div>
        </template>
      </div>
    </div>
  </div>
</template>
<script>
  import Search from './components/Search'
  import {
    FilterIcon,
    XIcon,
    PlayCircleIcon,
    SearchIcon,
    TrashIcon,
    ServerIcon,
    UploadCloudIcon,
    DownloadCloudIcon,
    PauseCircleIcon,
    SettingsIcon,
    LoaderIcon,
    SquareIcon,
    CheckSquareIcon,
    SaveIcon
  } from 'vue-feather-icons'
  import formatJSON from 'json-format-highlight'
  import msgpack from 'msgpack-lite'

  const HOST = location.port === '1234' ? 'localhost:3000' : location.host

  // TODO: Detect updates with npm
  export default {
    name: 'MinecraftPacketDebugger',
    components: {
      FilterIcon,
      XIcon,
      PlayCircleIcon,
      SearchIcon,
      TrashIcon,
      ServerIcon,
      UploadCloudIcon,
      DownloadCloudIcon,
      PauseCircleIcon,
      LoaderIcon,
      SettingsIcon,
      SquareIcon,
      CheckSquareIcon,
      SaveIcon,
      Search
    },
    methods: {
      formatJSON (...args) {
        return formatJSON(...args)
      },
      open (packet) {
        this.id_tab = 0

        if (this.id_open === packet) {
          return this.id_open = null
        }

        window.packet = packet
        this.id_open = packet
      },

      isFiltered (packet) {

        const words = this.search.query.split(' ').filter(s => s.length)
        const clientIndex = words.indexOf('to:client')
        const serverIndex = words.indexOf('to:server')
        const toClient = !!~clientIndex && !!words.splice(clientIndex, 1).length
        const toServer = !!~serverIndex && !!words.splice(serverIndex, 1).length

        if (toClient && toServer) {
          return false
        }

        if (toClient && (packet.to !== 0)) {
          return false
        }

        if (toServer && (packet.to !== 1)) {
          return false
        }

        if (!words.length) {
          return !this.filters[packet.meta.name]
        } else if (!words.includes(packet.meta.name)) {
          return false
        }

        return true
      },

      startRecording () {
        this.packets = []
        this.record.state = 1
        this.record.messageQueue = []

        this.ws = new WebSocket(`ws://${HOST}/ws`)

        this.ws.onmessage = (message) => {
          requestAnimationFrame(() => {
            if (this.record.messageQueue.length > 2048) {
              this.stopRecording()
            }

            this.record.messageQueue.push(message.data)
          })
        }
      },
      stopRecording () {
        if (this.ws) {
          this.ws.close()
          this.ws = null
          this.record.state = 2

          const copyPackets = async () => {
            if (this.record.messageQueue.length === 0) {
              this.record.state = 0
              return
            }

            const chunk = this.record.messageQueue.splice(0, 32)
            const arrayBuffers = await Promise.all(chunk.map(fn => fn.arrayBuffer()))

            const packets = arrayBuffers.map(buf => msgpack.decode(new Uint8Array(buf)).packet)
            this.packets.push(...packets)

            requestAnimationFrame(copyPackets)
          }

          requestAnimationFrame(copyPackets)
        }
      },
      settingsSelectPacket (packets) {
        for (const packet of packets) {
          this.settings.ignoredPackets.custom[packet] = true
        }

        this.$nextTick(() => {
          this.search.query = ''
        })
      },

      async openSettings () {
        const response = await fetch(`http://${HOST}/settings`)
        this.settings = await response.json()
      },
      async closeSettings () {
        const { settings: body } = this
        this.search.query = ''

        // Waiting for server to restart everything
        const res = await fetch(`http://${HOST}/settings`, {
          method: 'post',
          body: JSON.stringify(body)
        })

        const data = await res.json()

        if (data.error) {
          // TODO: Add some fancy notification
          console.error(data.error)
        } else {
          this.version = data.version
          this.host = body.server.host

          if (data.packets) {
            this.search.packets = data.packets
          }
        }

        this.settings = null
      },
    },
    data () {
      return {
        search: {
          query: '',
          packets: {
            toServer: [],
            toClient: []
          }
        },
        listening: false,
        id_open: null,
        version: '0.0.0',
        host: 'localhost',
        id_tab: 0,
        ws: null,
        settings: null,
        record: { messageQueue: [], state: -1 },
        tabs: [ 'Packet', 'Meta', 'Format' ],
        packets: [],
        filters: {}
      }
    },
    async created () {
      const res = await fetch(`http://${HOST}/host`)
      const data = await res.json()
      this.version = data.version
      this.host = data.host

      if (data.packets) {
        this.search.packets = data.packets
      }
    },
  }
</script>
